---
- name: Set root login shell to zsh
  user:
    name: root
    shell: /usr/bin/zsh

- name: Clone oh-my-zsh
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: /root/.oh-my-zsh
    version: "{{ omz_commit }}"

- name: Clone powerlevel10k theme
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: /root/.oh-my-zsh/custom/themes/powerlevel10k
    version: "{{ p10k_commit }}"

- name: Clone zsh-autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: /root/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    version: "{{ autosuggestions_commit }}"

- name: Clone zsh-syntax-highlighting
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: /root/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
    version: "{{ syntax_highlighting_commit }}"

- name: Install .zshrc
  copy:
    src: zshrc
    dest: /root/.zshrc
    mode: '0644'

- name: Install .p10k.zsh
  copy:
    src: p10k.zsh
    dest: /root/.p10k.zsh
    mode: '0644'

- name: Install .tmux.conf
  copy:
    src: tmux.conf
    dest: /root/.tmux.conf
    mode: '0644'

- name: Clone tpm
  git:
    repo: https://github.com/tmux-plugins/tpm.git
    dest: /root/.tmux/plugins/tpm
    version: "{{ tpm_commit }}"

- name: Install tmux plugins (headless)
  command: /root/.tmux/plugins/tpm/bin/install_plugins
  changed_when: false
