---
- name: Create admin user
  user:
    name: "{{ server_user }}"
    shell: /usr/bin/zsh
    groups: sudo
    append: yes
    create_home: yes

- name: Authorize GitHub keys
  authorized_key:
    user: "{{ server_user }}"
    key: "{{ lookup('url', 'https://github.com/{{ github_user }}.keys', split_lines=False) }}"

- name: Authorize local keys (optional)
  authorized_key:
    user: "{{ server_user }}"
    key: "{{ lookup('file', item) }}"
  with_fileglob: "{{ role_path }}/files/keys/*.pub"
  when: lookup('fileglob', role_path + '/files/keys/*.pub', q='first') | length > 0

- name: Passwordless sudo
  copy:
    dest: "/etc/sudoers.d/{{ server_user }}"
    content: "{{ server_user }} ALL=(ALL) NOPASSWD:ALL\n"
    mode: '0440'
    validate: 'visudo -cf %s'
